jumpstate = jstate_2wait
	flag_lastjumpframenext =false
	jcount = 0
	wcount_1 = 0
	wcount_2 = 0
	framecount_jump1 = 0
	framecount_jump1_jc = 0
	framecount_jump1_jc2 = 0
	framecount_jump1_jc3 = 0
	framecount_pause = 0
	framecount_jump2 = 0
	framecount_jump2_jc = 0
	framecount_jump2_jc2 = 0
	framecount_pause2 = 0
